### ISSUE TITLE
can you release the browser extension yet ?

### ISSUE THREAD

**Issue by beppe9000** [paper-materials-crowd-sourced/materials#2]

**Comment by ThomasAy** [comment]
The readme.md says explicitly:

>Currently, there is no release file because we don't want to publish it before paper submission.

**Comment by JafarAkhondali** [comment]
@beppe9000 as @ThomasAy mentioned, it's not planned for publishing. But still you can install it on your browser.
For Firefox, visit `about:debugging` and choose "Load Temporary  Add-on"
For Chrom* based browsers, visit `chrome://extensions/`, then enable developer mode( at top right corner), then choose "Load unpacked"

**Comment by beppe9000** [comment]
> don't want to publish it before paper submission
Was the paper submitted? I have no idea how to check that...

Do I select the `manifest.json` file when using "Load Temporary Add-on" in Firefox ?

**Comment by JafarAkhondali** [comment]
@beppe9000  well, paper is submitted but it's currently under review, so we cant publish the extension
