### ISSUE TITLE
"Unrecognized manifest key 'applications'."

### ISSUE THREAD

**Issue by jhertel** [paper-materials-crowd-sourced/materials#3]
When installing on Chrome 78.0.3904.108 on Windows 10 using the description on https://github.com/paper-materials-crowd-sourced/materials/blob/master/web-extension/readme.md:

"Visit chrome://extensions/ and enable "developer mode". Then install this add-on via "Load unpacked" button.",

Chrome issues this error:

"Unrecognized manifest key 'applications'."

and highlights this part of the manifest in yellow:

```
  "applications": {
    "gecko": {
      "id": "papermaterial@papermaterial.com",
      "strict_min_version": "52.0",
      "update_url": "https://your_server/updates.json"
    }
  }

```
The extension does still work, though.

If this is on purpose, I suggest adding something like this in the readme.md file right after the instructions for installing in Chrome (in the same paragraph): 

"Chrome/Chromium might report an error about "Unrecognized manifest key 'applications'" after adding the extension. Please ignore this; the extension will still work despite this error. (The 'applications' key was added to make the extension work in Firefox)."

**Comment by paper-materials-crowd-sourced** [comment]
@jhertel Thanks for the report,
Yes, due to conflict between Chrom* and Firefox( [more info here](https://wiki.mozilla.org/WebExtensions/Applications) ), we had to use this key to make the manifest work in browsers without modifying the codes.
We'll add info in readme
